#Simple approach idk

output:main.c LinkedListString.c LinkedListString.h
	gcc -o output main.c LinkedListString.c

main.o:main.c LinkedListString.h
	gcc -c main.c
LinkedListString.o:LinkedListString.c LinkedListString.h
	gcc -c LinkedListString.c